export const API_ENDPOINTS = {
  auth: '/auth',
  authLogin: '/auth/login',
  users: '/users',
  students: '/students',
  studentAccess: (studentId: string) =>
    `/students/${encodeURIComponent(studentId)}/access`,
  attendance: '/attendance',
  attendancePreview: '/attendance/preview',
  attendanceSubmit: '/attendance/submit',
  attendanceMe: '/attendance/me',
  attendanceAdmin: '/attendance/admin',
  attendanceAdminExcel: '/attendance/admin/excel',
  locations: '/locations',
  locationVisits: '/locations/visits',
  locationVisitsExcel: '/locations/visits/excel',
  locationById: (id: string) => `/locations/${encodeURIComponent(id)}`,
  sessions: '/sessions',
  sessionsOpen: '/sessions/open',
  sessionById: (id: string) => `/sessions/${id}`,
  sessionQr: (id: string) => `/sessions/${id}/qr`,
  sessionClose: (id: string) => `/sessions/${id}/close`,
  sessionEdit: (id: string) => `/sessions/${id}/edit`,
  sessionDelete: (id: string) => `/sessions/${id}`,
  reports: '/reports',
  scanOrigin: '/runtime/scan-origin',
} as const;
